### ISSUE TITLE
Cannot install Pharo Launcher on Windows without admin rights

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#43]
Pharo Launcher installer forces you to get privilege elevation (admin) and does not run if you do not have it.

**Comment by demarey** [comment]
a Solution could be to only ask for the highest privileges a user can have and run the installer with it.

**Comment by demarey** [comment]
@vitormcruz could you test again the installer (same version number as only the packaging changed)? I updated it to use a more recent version of NSIS allowing to ask only for the highest privileges available for a user. It should solve the issue in your case.

**Comment by vitormcruz** [comment]
Hi @demarey, I tested againg and the problem remains the same.

**Comment by demarey** [comment]
@vitormcruz Thanks for testing. I missed the definition of macro checking  admin rights in the installer. I'm now able to test with a standard windows user and the last installer works without admin rights. But ... I first got a warning from windows with SmartScreen. By default, SmartScreen requires admin rights to run untrusted apps ...
Tell me if the fix is enough for you. I should check how to get a trusted app for SmartScreen.

**Comment by vitormcruz** [comment]
@demarey Thanks for the fix, it's now working, I can install even if not admin.
