### ISSUE TITLE
code presenter raises GTK critical warnings

### ISSUE THREAD

**Issue by demarey** [pharo-project/pharo-launcher#737]
In Pharo Launcer GTK, when you select an image, then edit scripts, select one script and try to edit it, the code presenter raises a GTK critical warning at each ley stroke.

```
(Pharo Launcher:51391): GLib-GObject-CRITICAL **: 12:51:55.204: g_object_get_valist: value location for 'gint' passed as NULL

(Pharo Launcher:51391): GLib-GObject-CRITICAL **: 12:51:55.273: value_lcopy_int: assertion 'int_p != NULL' failed

(Pharo Launcher:51391): GLib-GObject-CRITICAL **: 12:51:55.273: g_object_get_valist: value location for 'gint' passed as NULL

(Pharo Launcher:51391): GLib-GObject-CRITICAL **: 12:51:55.459: value_lcopy_int: assertion 'int_p != NULL' failed

(Pharo Launcher:51391): GLib-GObject-CRITICAL **: 12:51:55.459: g_object_get_valist: value location for 'gint' passed as NULL

(Pharo Launcher:51391): GLib-GObject-CRITICAL **: 12:51:55.564: value_lcopy_int: assertion 'int_p != NULL' failed

(Pharo Launcher:51391): GLib-GObject-CRITICAL **: 12:51:55.564: g_object_get_valist: value location for 'gint' passed as NULL

(Pharo Launcher:51391): GLib-GObject-CRITICAL **: 12:51:55.588: value_lcopy_int: assertion 'int_p != NULL' failed

```

**Comment by estebanlm** [comment]
I suspect this is related to the `GEnumeration` initialization problem, @demarey can you verify is this is fixed after the correct initialization ?

**Comment by demarey** [comment]
the problem is still there, even after `GEnumeration` initialization

**Comment by estebanlm** [comment]
this was tested where? windows or macOS?

**Comment by demarey** [comment]
macOs

**Comment by estebanlm** [comment]
this will be fixed backporting the trunk of gtk-bindings to PL branch. 
I *guess* this is straightforward, but I will check tomorrow.
